#!/bin/bash
./personCreate.sh
./personGet.sh
./authorCreate.sh
./authorGet.sh
./categoryCreate.sh
./categoryGet.sh
./tagCreate.sh
./tagGet.sh
./draftCreate.sh
./draftGet.sh
./draftFirstPublish.sh
./newsGet.sh
./commentCreate.sh
./commentGet.sh

./authorEdit.sh
./authorGet.sh
./categoryEdit.sh
./categoryGet.sh
./tagEdit.sh
./tagGet.sh
./draftEdit.sh
./draftGet.sh
./draftNextPublish.sh
./newsGet.sh
./commentEdit.sh
./commentGet.sh

./commentDelete.sh
./commentGet.sh
./newsDelete.sh
./newsGet.sh
./draftDelete.sh
./draftGet.sh
./tagDelete.sh
./tagGet.sh
./categoryDelete.sh
./categoryGet.sh
./authorDelete.sh
./authorGet.sh
./personDelete.sh
./personGet.sh
